### ISSUE TITLE
Improvement: No Success view

### ISSUE THREAD

**Issue by paarce** [jhonr1vera/rest-api-express#3]
<img width="1280" alt="Screenshot 2024-01-10 at 23 02 02" src="https://github.com/jhonr1vera/rest-api-express/assets/11846967/8d4d56ec-ea8e-4e00-bee2-6060b712107a">

Note: After creating a proper product, there was no a user friendly view to let the user know that the action was done as expected. The user could be redirected to the new product detail

**Comment by jhonr1vera** [comment]
All done, you can take a look. I chose a pop-ups to see if it was done correctly or not, also in another endpoints
